---
role_vars:
  # List of packages to install
  packages:
    []
    # - example-app
    # - example-cli

  # All symbolic links (both App config and Shell config)
  symlinks:
    - src: "role"
      dest: ".config/role"
    - src: "role-conf-d/99-role.zsh"
      dest: ".config/zsh/conf.d/99-role.zsh"

  # Directories that must exist before linking
  config_dirs:
    - .config
    - .config/zsh/conf.d
