---
role_vars:
  # Install Aerospace via specific tap
  packages:
    - nikitabobko/tap/aerospace

  # Individual Link Rule
  symlinks:
    - src: "aerospace/aerospace.toml"
      dest: ".config/aerospace/aerospace.toml"
    - src: "aerospace-conf-d/53-aerospace.zsh"
      dest: ".config/zsh/conf.d/53-aerospace.zsh"

  # Ensure directories exist
  config_dirs:
    - .config/aerospace
    - .config/zsh/conf.d
