---
role_vars:
  # List of packages to install
  packages:
    - zsh
    - powerlevel10k

  # List of symbolic links to create
  symlinks:
    - src: "zsh/.zshrc"
      dest: ".zshrc"
    - src: "zsh/.p10k.zsh"
      dest: ".p10k.zsh"
    - src: "zsh-conf-d/00-p10k.zsh"
      dest: ".config/zsh/conf.d/00-p10k.zsh"

  # Directories that must exist before creating symlinks
  config_dirs:
    - .config/zsh/conf.d
