---
- import_tasks: ../../common/tasks/standard_role.yml

# 4. Install TPM
- name: Install TPM
  git:
    repo: "{{ role_vars.tpm.repo }}"
    dest: "{{ ansible_facts['user_dir'] }}/{{ role_vars.tpm.dest }}"
    version: master
  when: role_vars.tpm is defined
